apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: memos
  labels:
    app: memos
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuer }}
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - memos.abuniyyah.uk
      secretName: memos-tls
  rules:
  - host: memos.abuniyyah.uk
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: memos
            port:
              number: 80