replicaCount: 1

image:
  repository: 310829530244.dkr.ecr.eu-west-2.amazonaws.com/memos
  tag: f2826f910639c75f43c3dd887c127420d4d91dbd
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

containerPort: 8081